// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NssOrderTool.Database;

#nullable disable

namespace NssOrderTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708140158_ShortenEntityComments")]
    partial class ShortenEntityComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NssOrderTool.Models.Entities.AliasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("自動採番ID");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias_name")
                        .HasComment("観測時に入力された別名");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<string>("TargetPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_player_id")
                        .HasComment("紐付け先プレイヤーID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.ToTable("Aliases", t =>
                        {
                            t.HasComment("プレイヤー別名を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("participant_id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("参加プレイヤーID");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank")
                        .HasComment("最終順位");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id")
                        .HasComment("アリーナセッションID");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_index")
                        .HasComment("座席番号（0〜7）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.Property<int>("WinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win_count")
                        .HasComment("獲得勝利数");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId");

                    b.ToTable("ArenaParticipants", t =>
                        {
                            t.HasComment("アリーナ参加者の結果を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_number")
                        .HasComment("ラウンド番号（1〜14）");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id")
                        .HasComment("アリーナセッションID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.Property<int>("WinningTeam")
                        .HasColumnType("INTEGER")
                        .HasColumnName("winning_team")
                        .HasComment("勝利チーム（0:無効 1:Blue 2:Orange）");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ArenaRounds", t =>
                        {
                            t.HasComment("アリーナラウンドの結果を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_valid")
                        .HasComment("結果有効フラグ");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memo")
                        .HasComment("自由記述メモ");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id")
                        .HasComment("所属シーズンID");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date")
                        .HasComment("実施日時");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("ArenaSessions", t =>
                        {
                            t.HasComment("アリーナ対戦セッションを管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("detail_id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id")
                        .HasComment("親観測データID");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index")
                        .HasComment("出現順序（0,1,2...）");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("観測プレイヤーID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ObservationDetails", t =>
                        {
                            t.HasComment("観測データの明細（プレイヤー順序）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("observation_time")
                        .HasComment("観測日時");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.ToTable("Observations", t =>
                        {
                            t.HasComment("プレイヤー出現順序の観測データを管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("プレイヤーID（UUID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen")
                        .HasComment("初回観測日時");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("アクティブフラグ");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_played_at")
                        .HasComment("最終対戦日時");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memo")
                        .HasComment("自由記述メモ");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("表示名");

                    b.Property<double>("RateMean")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_mean")
                        .HasComment("現在のレート平均値（μ）");

                    b.Property<double>("RateSigma")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_sigma")
                        .HasComment("現在のレート不確実性（σ）");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_matches")
                        .HasComment("通算試合数");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_wins")
                        .HasComment("通算勝利数");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.ToTable("Players", t =>
                        {
                            t.HasComment("プレイヤーの基本情報と成績を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerSeasonRatingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("対象プレイヤーID");

                    b.Property<double>("RateMean")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_mean")
                        .HasComment("シーズン内レート平均値（μ）");

                    b.Property<double>("RateSigma")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_sigma")
                        .HasComment("シーズン内レート不確実性（σ）");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id")
                        .HasComment("対象シーズンID");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_matches")
                        .HasComment("シーズン内試合数");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_wins")
                        .HasComment("シーズン内勝利数");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PlayerSeasonRatings", t =>
                        {
                            t.HasComment("シーズン別レート・成績のスナップショットを管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.RateHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("自動採番ID");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("対象プレイヤーID");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL")
                        .HasComment("記録時点のレート値");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasComment("記録日時");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id")
                        .HasComment("所属シーズンID");

                    b.HasKey("Id");

                    b.ToTable("RateHistories", t =>
                        {
                            t.HasComment("プレイヤーのレート変動履歴テーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("自動採番ID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date")
                        .HasComment("終了日時（進行中はnull）");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("進行中フラグ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("シーズン表示名");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date")
                        .HasComment("開始日時");

                    b.HasKey("Id");

                    b.ToTable("Seasons", t =>
                        {
                            t.HasComment("レート集計期間（シーズン）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SequencePairEntity", b =>
                {
                    b.Property<string>("PredecessorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("predecessor_id")
                        .HasComment("前方プレイヤーID");

                    b.Property<string>("SuccessorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("successor_id")
                        .HasComment("後方プレイヤーID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frequency")
                        .HasComment("累計出現頻度");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("PredecessorId", "SuccessorId");

                    b.ToTable("SequencePairs", t =>
                        {
                            t.HasComment("出現順序ペアの頻度統計テーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaParticipantEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NssOrderTool.Models.Entities.ArenaSessionEntity", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaRoundEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.ArenaSessionEntity", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.SeasonEntity", "Season")
                        .WithMany("ArenaSessions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationDetailEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.ObservationEntity", "Observation")
                        .WithMany("Details")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NssOrderTool.Models.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerSeasonRatingEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NssOrderTool.Models.Entities.SeasonEntity", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationEntity", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SeasonEntity", b =>
                {
                    b.Navigation("ArenaSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
