// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NssOrderTool.Database;

#nullable disable

namespace NssOrderTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703085454_AddEntityComments")]
    partial class AddEntityComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NssOrderTool.Models.Entities.AliasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("サロゲートキー（自動インクリメントID）");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias_name")
                        .HasComment("観測時に入力されたプレイヤーの別名");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<string>("TargetPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_player_id")
                        .HasComment("紐付け先となる正規のプレイヤーID（Playersテーブルの外部キー）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("Id");

                    b.ToTable("Aliases", t =>
                        {
                            t.HasComment("プレイヤーの別名（エイリアス）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("participant_id")
                        .HasComment("参加情報のサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("参加したプレイヤーのID（Playersテーブルの外部キー）");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank")
                        .HasComment("このセッションでの最終順位");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id")
                        .HasComment("紐づくアリーナセッションのID（ArenaSessionsテーブルの外部キー）");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_index")
                        .HasComment("セッション内での座席番号・配置インデックス（通常 0〜7）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.Property<int>("WinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win_count")
                        .HasComment("このセッションで獲得した最終的な勝利数");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId");

                    b.ToTable("ArenaParticipants", t =>
                        {
                            t.HasComment("アリーナセッションに参加する各プレイヤーの情報と最終結果（座席、勝利数、順位など）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_id")
                        .HasComment("ラウンドのサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_number")
                        .HasComment("セッション内でのラウンド進行番号（通常 1 〜 14）");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id")
                        .HasComment("紐づくアリーナセッションのID（ArenaSessionsテーブルの外部キー）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.Property<int>("WinningTeam")
                        .HasColumnType("INTEGER")
                        .HasColumnName("winning_team")
                        .HasComment("ラウンドの勝利チーム（0: 引き分け/無効, 1: Blueチーム, 2: Orangeチーム）");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ArenaRounds", t =>
                        {
                            t.HasComment("アリーナセッション内の各ラウンド（局所的な対戦）の結果を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id")
                        .HasComment("セッションのサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_valid")
                        .HasComment("セッションの対戦結果が有効かどうかのフラグ（無効試合の除外用）");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memo")
                        .HasComment("セッションに関する自由記述のメモ");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id")
                        .HasComment("このセッションが属するシーズンのID（Seasonsテーブルの外部キー）");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_date")
                        .HasComment("セッションが実際に実施・観測された日時");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("ArenaSessions", t =>
                        {
                            t.HasComment("アリーナ（対戦環境）の1セッション（試合単位）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("detail_id")
                        .HasComment("観測詳細データのサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id")
                        .HasComment("紐づく親観測データのID（Observationsテーブルの外部キー）");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index")
                        .HasComment("観測されたプレイヤーの順番・配置インデックス（0, 1, 2...）");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("観測されたプレイヤーのID（Playersテーブルの外部キー）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ObservationDetails", t =>
                        {
                            t.HasComment("1回の観測データに含まれる個々のプレイヤーとその順序（子レコード）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id")
                        .HasComment("観測データのサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("observation_time")
                        .HasComment("観測が実行・記録された日時");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("Id");

                    b.ToTable("Observations", t =>
                        {
                            t.HasComment("プレイヤーの出現順序などの観測データ（親レコード）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("プレイヤーの一意な識別子（UUID文字列）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen")
                        .HasComment("システム内でプレイヤーが初めて観測された日時");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("プレイヤーが現在アクティブかどうかのフラグ");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_played_at")
                        .HasComment("最後に試合を行った日時");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memo")
                        .HasComment("プレイヤーに関する自由記述のメモ");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("プレイヤーの正式な表示名");

                    b.Property<double>("RateMean")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_mean")
                        .HasComment("プレイヤーの現在の内部レート予測平均値（μ）");

                    b.Property<double>("RateSigma")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_sigma")
                        .HasComment("プレイヤーの現在のレート不確実性（σ）");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_matches")
                        .HasComment("通算試合数");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_wins")
                        .HasComment("通算勝利数");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("Id");

                    b.ToTable("Players", t =>
                        {
                            t.HasComment("正規のプレイヤー基本情報および通算成績・最新レートを管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerSeasonRatingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("シーズン別レート情報のサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id")
                        .HasComment("対象プレイヤーのID（Playersテーブルの外部キー）");

                    b.Property<double>("RateMean")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_mean")
                        .HasComment("このシーズンにおけるレート予測平均値（μ）");

                    b.Property<double>("RateSigma")
                        .HasColumnType("REAL")
                        .HasColumnName("rate_sigma")
                        .HasComment("このシーズンにおけるレート不確実性（σ）");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id")
                        .HasComment("対象シーズンのID（Seasonsテーブルの外部キー）");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_matches")
                        .HasComment("このシーズンでの累計試合数");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_wins")
                        .HasComment("このシーズンでの累計勝利数");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PlayerSeasonRatings", t =>
                        {
                            t.HasComment("プレイヤーのシーズンごとのレート情報および成績（スナップショット）を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.RateHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("レート履歴のサロゲートキー（自動インクリメントID）");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("対象プレイヤーのID（Playersテーブルの外部キー）");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL")
                        .HasComment("記録時点での計算済みレート値");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasComment("レートが変動・記録された日時");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id")
                        .HasComment("この履歴が属するシーズンのID（Seasonsテーブルの外部キー）");

                    b.HasKey("Id");

                    b.ToTable("RateHistories", t =>
                        {
                            t.HasComment("プレイヤーのレート変動履歴を時系列で記録するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("シーズンのサロゲートキー（自動インクリメントID）");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date")
                        .HasComment("シーズンの終了日時（現在進行中のシーズンの場合は null）");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("現在アクティブに進行しているシーズンかどうかのフラグ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("シーズンの表示名（例: 'Season 1'、'2026 Spring' など）");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date")
                        .HasComment("シーズンの開始日時");

                    b.HasKey("Id");

                    b.ToTable("Seasons", t =>
                        {
                            t.HasComment("レート計算や集計の期間区切りとなる「シーズン」の情報を管理するテーブル");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SequencePairEntity", b =>
                {
                    b.Property<string>("PredecessorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("predecessor_id")
                        .HasComment("前方に位置するプレイヤーのID");

                    b.Property<string>("SuccessorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("successor_id")
                        .HasComment("後方に位置するプレイヤーのID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("レコード作成日時");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frequency")
                        .HasComment("この順序ペアが観測された累計頻度（回数）");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasComment("論理削除フラグ（trueで削除済み）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("レコード最終更新日時");

                    b.HasKey("PredecessorId", "SuccessorId");

                    b.ToTable("SequencePairs", t =>
                        {
                            t.HasComment("プレイヤーの出現順序ペア（前後関係）の出現頻度統計");
                        });
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaParticipantEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NssOrderTool.Models.Entities.ArenaSessionEntity", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaRoundEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.ArenaSessionEntity", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.SeasonEntity", "Season")
                        .WithMany("ArenaSessions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationDetailEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.ObservationEntity", "Observation")
                        .WithMany("Details")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NssOrderTool.Models.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerSeasonRatingEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NssOrderTool.Models.Entities.SeasonEntity", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationEntity", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SeasonEntity", b =>
                {
                    b.Navigation("ArenaSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
