// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NssOrderTool.Database;

#nullable disable

namespace NssOrderTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NssOrderTool.Models.Entities.AliasEntity", b =>
                {
                    b.Property<string>("AliasName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("alias_name");

                    b.Property<string>("TargetPlayerId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("target_player_id");

                    b.HasKey("AliasName");

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("round_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int")
                        .HasColumnName("round_number");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("WinningTeam")
                        .HasColumnType("int")
                        .HasColumnName("winning_team");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ArenaRounds");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PlayerIdsCsv")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("player_ids_csv");

                    b.HasKey("Id");

                    b.ToTable("ArenaSessions");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ObservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("observation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("observation_time");

                    b.Property<string>("OrderedList")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ordered_list");

                    b.HasKey("Id");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.SequencePairEntity", b =>
                {
                    b.Property<string>("PredecessorId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("predecessor_id");

                    b.Property<string>("SuccessorId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("successor_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.HasKey("PredecessorId", "SuccessorId");

                    b.ToTable("SequencePairs");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaRoundEntity", b =>
                {
                    b.HasOne("NssOrderTool.Models.Entities.ArenaSessionEntity", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NssOrderTool.Models.Entities.ArenaSessionEntity", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
