ArenaParticipants {
    int participant_id PK
    int session_id FK
    string player_id FK
    int slot_index
    int win_count
    int rank
    bool is_deleted
    datetime created_at
    datetime updated_at
  }
